// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjwzizjndpkkkuzmpiei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdqd3ppempuZHBra2t1em1waWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzY4MDksImV4cCI6MjA2MDk1MjgwOX0.FIxYmTFzHWGudzvcc4CJ388RmX6rzi8JOdZrOg6EjXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);